Repository nsftx/vue-cli-plugin-nsoft, pull requests merged in 2019-04, with the labels that each got.

#32 Rename usage of components with PascalCase
  generator/template/default/src/App.vue
  generator/template/default/src/pages/Home.vue
Labels: bug

#34 Fix env handling #33
  generator/template/default/.env
  generator/template/default/.env.development
  generator/template/default/.env.production
  generator/template/default/.env.staging
  generator/template/default/config/_env.js
  generator/template/default/config/index.js
  generator/template/default/src/api/http.js
Labels: bug, enhancement

#35 Create Redirects File
  generator/template/default/public/_redirects
Labels: enhancement
